//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }

        public int IdUser { get; set; }
        [Required(ErrorMessage = "Tên tài khoản không được để trống.")]
        [StringLength(20, ErrorMessage = "Tên tài khoản phải từ 6 kí tự", MinimumLength = 6)]
        public string username { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được để trống.")]
        [StringLength(20, ErrorMessage = "Mật khẩu phải từu 8 kí tự", MinimumLength = 8)]
        public string password { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Bạn chưa nhập lại mật khẩu.")]
        [System.ComponentModel.DataAnnotations.Compare("password", ErrorMessage = "Mật khẩu không trùng khớp, vui lòng nhập lại.")]
        public string confirmPassword { get; set; }
        public string role { get; set; }
        [Required(ErrorMessage = "Họ tên không được để trống.")]
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được để trống.")]
        public string phone { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
